#!/bin/bash

intern="eDP-1"
extern="HDMI-1"

# Change monitor
if xrandr | grep "$extern disconnected"; then
    xrandr --output "$extern" --off --output "$intern" --auto
else
    xrandr --output "$intern" --off --output "$extern" --auto 
    xrandr --output "$extern" --mode 1920x1080
fi

# Refresh wallpaper
nitrogen --restore --sync
